# CATSvsBADTUNA docker-compose file
version: '2'
services:      
  phpapache:
    image: php:5.6-apache
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
      
    